const IMG_BASE_URL = "/src/assets/images/modules";

export const modules = [
  {
    id: 1,
    name: "Salud Económica",
    path: "/salud-economica",
    image: `${IMG_BASE_URL}/salud-economica.png`,
    completed: false,
  },
  {
    id: 2,
    name: "Yo llevo mis cuentas",
    path: "/yo-llevo-mis-cuentas",
    image: `${IMG_BASE_URL}/yo-llevo-mis-cuentas.png`,
    completed: false,
  },
  {
    id: 3,
    name: "Yo ahorro",
    path: "/yo-ahorro",
    image: `${IMG_BASE_URL}/yo-ahorro.png`,
    completed: false,
  },
  {
    id: 4,
    name: "Deudas",
    path: "/deudas",
    image: `${IMG_BASE_URL}/deudas-sanas.png`,
    completed: false,
  },
  {
    id: 5,
    name: "Tentaciones",
    path: "/tentaciones",
    image: `${IMG_BASE_URL}/tentaciones.png`,
    completed: false,
  },
  {
    id: 6,
    name: "Yo me aseguro",
    path: "/yo-me-aseguro",
    image: `${IMG_BASE_URL}/yo-me-aseguro.png`,
    completed: false,
  },
  {
    id: 7,
    name: "Servicios Financieros",
    path: "/servicios-financieros",
    image: `${IMG_BASE_URL}/servicios-financieros.png`,
    completed: false,
  },
  {
    id: 8,
    name: "Trabajo en Comunidad",
    path: "/trabajo-en-comunidad",
    image: `${IMG_BASE_URL}/trabajo-en-comunidad.png`,
    completed: false,
  },
  {
    id: 9,
    name: "Cajero automático",
    path: "/cajero-automatico",
    image: `${IMG_BASE_URL}/cajero-automatico.png`,
    completed: false,
  },
  {
    id: 10,
    name: "Recomendaciones de Seguridad",
    path: "/recomendaciones-de-seguridad",
    image: `${IMG_BASE_URL}/recomendaciones-de-seguridad.png`,
    completed: false,
  },
  {
    id: 11,
    name: "Mi Aprendizaje",
    path: "/mi-aprendizaje",
    image: `${IMG_BASE_URL}/mi-aprendizaje.png`,
    completed: false,
  },
];
